services:
  - type: web
    name: gomeria
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:w2INc/JToPZbPD0Sdu/V3YZ/fy4IWZykvJOrlVw24pU= 
      - key: DB_CONNECTION
        value: sqlite
